#!/usr/bin/env python

"""
nuvifiles.py - Data for icon files.
"""

cacheBMP = """
Qk32BgAAAAAAADYAAAAoAAAAGAAAABgAAAABABgAAAAAAMAGAAATCwAAEwsAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AAAA
AAAAAAAAAP//AAAAAAAAAAAAAAAAAP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//
AP//AP//AP//AAAAAAAAAAAAAP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AAAAAAAAAAAAAP//
AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//
AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AAAA
AAAAAAAAAAAAAP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AAAAAAAAAAAAAP//
AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//
AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//
AP//AAAAAAAAAAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//
AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AP//
AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//
AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAA
AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//
AP//AAAAAAAAAAAAAP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAA
AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//
AP//AAAAAAAAAAAAAAAAAP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AAAA
AAAAAAAAAP//AP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AP//AAAAAAAAAAAAAP//AP//AP//
AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AP//AAAAAAAAAAAAAAAAAP//AP//AAAAAAAA
AAAAAP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAP//AP//AAAAAAAAAAAA
AAAAAP//AAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AAAAAAAA
AAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//AP//AP//AP//AP//
AP//AP//AP//AP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AP//AP//AP//AP//AP//
AP//AP//AP//AP//AP//AP//AP//AP//AP//AP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
"""

cacheJPG = """
/9j/4AAQSkZJRgABAQEASABIAAD/4QBoRXhpZgAASUkqAAgAAAAEABoBBQABAAAAPgAAABsBBQAB
AAAARgAAACgBAwABAAAAAgAAADEBAgARAAAATgAAAAAAAABIGQEA6AMAAEgZAQDoAwAAUGFpbnQu
TkVUIHYzLjUuNQAA/9sAQwACAQEBAQECAQEBAgICAgIEAwICAgIFBAQDBAYFBgYGBQYGBgcJCAYH
CQcGBggLCAkKCgoKCgYICwwLCgwJCgoK/9sAQwECAgICAgIFAwMFCgcGBwoKCgoKCgoKCgoKCgoK
CgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoK/8AAEQgAGAAYAwEiAAIRAQMRAf/E
AB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAE
EQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZH
SElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1
tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEB
AQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXET
IjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFla
Y2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG
x8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+Gf2Ff2Ff2ePgf8A
s8fDX/goN/wUG/Zq/wCFq/s7/FX7TpvifxPoepavZ6l8K9St9Xu9PhubiHT7pPtmn3HlR75NpdXY
IgWRIotQ/XD/AIcFf8EFP+Fa/wDC5v8AhnbQ/wDhD/7D/tr/AISv/hbWuf2b/Zvk+f8AbftX9p+V
9n8n97527Zs+bOOaP+CBX/Ctf+HCnw6/4XN/Yf8Awh/9h+Lf+Er/AOEn8n+zf7N/t3VvtX2vz/3X
2fyd/meZ8mzdu4zX5kf+Hx/4dPf8Lx/z/wBRT/hH/wC1/wDP9q1/nfned8beI3G2cYbDZxisvll+
KrUm6VarGliKUatSNKjRpRqQj9e5YctKlGyxKTlJwqQnOr9bSpYbCYanKVOM+eKeqV07K7bt8Pd9
PTbhv26v2Ff2ePjh+zx8Sv8AgoN/wT5/Zq/4VV+zv8Kvs2m+GPE+ualq95qXxU1K41e00+a5t4dQ
un+x6fb+bJsk2h2dSjhpHli08r9cP+C+v/Ctf+HCnxF/4Uz/AGH/AMIf/YfhL/hFP+EY8n+zf7N/
t3Sfsv2TyP3X2fydnl+X8mzbt4xRX9GfRt42zHjngnF4nFc/LRxU6NNVZyq1VThSoyXtas/eqVHK
cpTk7JOTjCMKcYwj5GcYaGGxMYxtrFN2Vle72XRf1ufiv+z3/wAFQ/hrr/7PHwj/AOCfP7Z1v45s
f2d/hx9v1Lxh4Y+GCQy6l8RNSl1e41C3tr6aa5tfsmnxfaFzHEzuXgL5Ej28tl+m/wDxFT/8Ejv+
Fa/8KZ/4ZO+Kv/CH/wBh/wBi/wDCKf8ACCaB/Zv9m+T5H2L7L/aflfZ/J/deTt2bPlxjiiivY4s8
APDzjHFKtjYVYpTqVVGnUcI+1qzc6lVpLWpOT1m23yxjBNQhGKzoZri8PG0bbJaq+i0S9D8yP2hP
+Cofw10D9nj4uf8ABPn9jG38c337O/xH+wal4P8ADHxPSGLUvh3qUWr2+oXFtYzQ3N19r0+X7O2I
5WRw84fJkS4lvSiiv0zh3hnKeF8LUo4KLvVl7SpKTvKpU5IQdSb0vOUYR55WvOSc5XnKUnxVq1Sv
JOXTReS3svLU/9k=
"""

# vim:set tw=0:
